#ifndef PROGRAM_H
    #define PROGRAM_H
    const int PROGRAM_INPUT_BUFFER_SIZE = 30;
    enum ProgramStatus
    {
        PROGRAM_STATE_MENU,
        PROGRAM_STATE_EXIT,
        PROGRAM_STATE_SOLVE,
        PROGRAM_STATE_ERROR,
        PROGRAM_STATE_CALCULATION,
        PROGRAM_STATE_HELP,
        PROGRAM_STATE_BUFFER_OVERFLOW,
        PROGRAM_STATE_TEST_CREATE
    };

#endif
